spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: metrics
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
