version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - smarthome-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/smarthome-init.sql
      - ./metrics/init.sql:/docker-entrypoint-initdb.d/metrics-init.sql
      - ./device-management/init.sql:/docker-entrypoint-initdb.d/management-init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "smarthome"]
      interval: 3s
      timeout: 6s
      retries: 3
      start_period: 15s

  temperature-api:
    container_name: temperature-app
    build:
      context: ./temperature
      dockerfile: Dockerfile
    # image: localhost/temperature:latest
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smarthome-network

  rabbitmq:
    container_name: smarthome-rabbitmq
    image: rabbitmq:4.1-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - smarthome-network
    environment:
      RABBITMQ_DEFAULT_USER: user01
      RABBITMQ_DEFAULT_PASS: 12345678
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  metrics:
    build:
      context: .
      dockerfile: Dockerfile
    # image: localhost/metrics:latest
    container_name: metrics-app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics
      POSTGRES_HOST: smarthome-postgres
      RABBITMQ_USER: user01
      RABBITMQ_PASSWORD: 12345678
      RABBITMQ_HOST: smarthome-rabbitmq
    ports:
      - "8082:8080"
    restart: always
    networks:
      - smarthome-network

  management:
    build:
      context: .
      dockerfile: Dockerfile
    # image: localhost/management:latest
    container_name: management-app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: management
      POSTGRES_HOST: smarthome-postgres
      RABBITMQ_USER: user01
      RABBITMQ_PASSWORD: 12345678
      RABBITMQ_HOST: smarthome-rabbitmq
      SMART_HOME_SERVICE_URL: http://smarthome-app:8080
    ports:
      - "8083:8080"
    restart: always
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    # image: localhost/smarthome-app:latest
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@smarthome-postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-app:8081
    ports:
      - "8080:8080"
    restart: always
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge